using System.Collections;using System.Collections.Generic;using UnityEngine;
namespace LumiAdventure {
public sealed class LumiKuramaMotion:MonoBehaviour {
 LumiGame game;LumiEnemy owner;Animation animationPlayer;Transform mouth;Vector3 previous;GameObject charge;Coroutine routine;
 SkinnedMeshRenderer hitSkin;Transform[] bones;BoxCollider bodyHitbox;readonly List<int>[] hitVertices=new List<int>[37];readonly BoxCollider[] hitColliders=new BoxCollider[37];float nextHitbox;List<int>[] referenceVertices;Vector3[] sourceVertices;BoneWeight[] skinWeights;Matrix4x4[] bindPoses,posedMatrices;
 public BoxCollider BodyHitbox=>bodyHitbox;
 void CreateBodyHitbox(){hitSkin=GetComponentInChildren<SkinnedMeshRenderer>();if(hitSkin==null)return;sourceVertices=hitSkin.sharedMesh.vertices;skinWeights=hitSkin.sharedMesh.boneWeights;bindPoses=hitSkin.sharedMesh.bindposes;bones=hitSkin.bones;posedMatrices=new Matrix4x4[bones.Length];for(int g=0;g<hitVertices.Length;g++)hitVertices[g]=new List<int>();var weights=skinWeights;for(int i=0;i<weights.Length;i++){var w=weights[i];int index=w.boneIndex0;float weight=w.weight0;if(w.weight1>weight){index=w.boneIndex1;weight=w.weight1;}if(w.weight2>weight){index=w.boneIndex2;weight=w.weight2;}if(w.weight3>weight)index=w.boneIndex3;string bone=bones[index].name;int split=bone.IndexOf('_');int n;int group=0;if(bone.StartsWith("Bone")&&split>4&&int.TryParse(bone.Substring(4,split-4),out n)&&n>=2&&n<=37)group=n-1;hitVertices[group].Add(i);}referenceVertices=new List<int>[hitVertices.Length];for(int g=0;g<hitVertices.Length;g++)referenceVertices[g]=new List<int>(hitVertices[g]);var sample=LumiHitHullSamples.Load(hitSkin.sharedMesh,"Kurama");if(sample!=null)foreach(var group in hitVertices)group.RemoveAll(i=>!sample[i]);for(int g=0;g<hitVertices.Length;g++)if(hitVertices[g].Count>0)hitColliders[g]=gameObject.AddComponent<BoxCollider>();bodyHitbox=hitColliders[0];UpdateBodyHitbox();}
 void UpdateBodyHitboxReference(){if(bodyHitbox==null)return;var space=transform.worldToLocalMatrix;for(int b=0;b<posedMatrices.Length;b++)posedMatrices[b]=space*bones[b].localToWorldMatrix*bindPoses[b];for(int g=0;g<hitVertices.Length;g++){if(hitColliders[g]==null)continue;Bounds bounds=new Bounds();bool first=true;foreach(int i in referenceVertices[g]){var w=skinWeights[i];Vector3 v=sourceVertices[i];Vector3 point=posedMatrices[w.boneIndex0].MultiplyPoint3x4(v)*w.weight0;if(w.weight1>0)point+=posedMatrices[w.boneIndex1].MultiplyPoint3x4(v)*w.weight1;if(w.weight2>0)point+=posedMatrices[w.boneIndex2].MultiplyPoint3x4(v)*w.weight2;if(w.weight3>0)point+=posedMatrices[w.boneIndex3].MultiplyPoint3x4(v)*w.weight3;if(first){bounds=new Bounds(point,Vector3.zero);first=false;}else bounds.Encapsulate(point);}hitColliders[g].center=bounds.center;hitColliders[g].size=bounds.size+Vector3.one*(g==0?.08f:.04f);}}
 void UpdateBodyHitbox(){if(bodyHitbox==null)return;var space=transform.worldToLocalMatrix;for(int b=0;b<posedMatrices.Length;b++)posedMatrices[b]=space*bones[b].localToWorldMatrix*bindPoses[b];for(int g=0;g<hitVertices.Length;g++){if(hitColliders[g]==null)continue;Vector3 min=new Vector3(float.PositiveInfinity,float.PositiveInfinity,float.PositiveInfinity),max=-min;foreach(int i in hitVertices[g]){var w=skinWeights[i];Vector3 v=sourceVertices[i];Vector3 point=posedMatrices[w.boneIndex0].MultiplyPoint3x4(v)*w.weight0;if(w.weight1>0)point+=posedMatrices[w.boneIndex1].MultiplyPoint3x4(v)*w.weight1;if(w.weight2>0)point+=posedMatrices[w.boneIndex2].MultiplyPoint3x4(v)*w.weight2;if(w.weight3>0)point+=posedMatrices[w.boneIndex3].MultiplyPoint3x4(v)*w.weight3;min=Vector3.Min(min,point);max=Vector3.Max(max,point);}hitColliders[g].center=(min+max)*.5f;hitColliders[g].size=max-min+Vector3.one*(g==0?.08f:.04f);}}
 void LateUpdate(){if(game!=null&&game.IsPlaying&&Time.time>=nextHitbox){float distance=game.Player!=null?(game.Player.transform.position-transform.position).sqrMagnitude:0;nextHitbox=Time.time+(distance>1600?Random.Range(.22f,.28f):Random.Range(.085f,.115f));UpdateBodyHitbox();}}
 public bool Busy=>routine!=null;
 public void Initialize(LumiGame session,LumiEnemy enemy){game=session;owner=enemy;LumiHitHullSamples.ConfigureDamageLayer(gameObject);animationPlayer=GetComponentInChildren<Animation>();previous=transform.position;if(bodyHitbox==null)CreateBodyHitbox();nextHitbox=Time.time+Random.Range(0f,.1f);if(hitSkin!=null)hitSkin.updateWhenOffscreen=false;foreach(var bone in GetComponentsInChildren<Transform>())if(bone.name.StartsWith("Shootpoint_017")){mouth=bone;break;}}
 public Vector3 MouthPoint=>mouth!=null?mouth.position:transform.TransformPoint(new Vector3(0,2,.75f));
 void Update(){if(game==null||!game.IsPlaying||owner==null||!owner.IsAlive)return;float speed=(transform.position-previous).magnitude/Mathf.Max(Time.deltaTime,.001f);previous=transform.position;if(!Busy && animationPlayer!=null){string clip=speed>.2f?"Run":"Idle";if(animationPlayer[clip]!=null){animationPlayer[clip].speed=clip=="Run"?Mathf.Clamp(speed/2.5f,.65f,1.5f):1;if(!animationPlayer.IsPlaying(clip))animationPlayer.CrossFade(clip,.15f);}}}
 public void Fire(Component target,int damage){if(Busy||target==null)return;routine=StartCoroutine(Shoot(target,damage));}
 IEnumerator Shoot(Component target,int damage){if(animationPlayer!=null&&animationPlayer["Attack"]!=null){animationPlayer["Attack"].speed=animationPlayer["Attack"].length/2;animationPlayer.CrossFade("Attack",.12f);}charge=LumiTailedBeastBomb.CreateVisual(transform,"Kurama charging small tailed beast bomb");float age=0;while(age<1.15f && owner!=null && owner.IsAlive){if(game.IsPlaying){age+=Time.deltaTime;charge.transform.position=MouthPoint+owner.transform.forward*.25f;charge.transform.localScale=Vector3.one*Mathf.Lerp(.1f,.55f,age/1.15f);charge.transform.Rotate(0,180*Time.deltaTime,70*Time.deltaTime);}yield return null;}if(owner==null||!owner.IsAlive){CancelAttack();yield break;}
 if(target!=null && ((ILumiDamageable)target).IsAlive){Vector3 at=target.transform.position+Vector3.up*.9f;GameObject shot=charge;charge=null;shot.name="Kurama small tailed beast bomb";shot.transform.SetParent(owner.transform.parent,true);shot.AddComponent<LumiTailedBeastBomb>().Initialize(game,owner.transform,(at-shot.transform.position).normalized,damage);game.Audio.Play("chakra",.7f);}else if(charge!=null){Destroy(charge);charge=null;}
 yield return new WaitForSeconds(.85f);routine=null;}
 public void CancelAttack(){if(routine!=null)StopCoroutine(routine);routine=null;if(charge!=null)Destroy(charge);charge=null;if(animationPlayer!=null&&animationPlayer["Idle"]!=null)animationPlayer.CrossFade("Idle",.15f);}
 void OnDisable(){CancelAttack();}
}
}








