using System;using System.IO;using System.Collections;using System.Collections.Generic;using UnityEditor;using UnityEngine;using LumiAdventure;
[InitializeOnLoad] public static class LumiBijuuPreview {
 const string Request="Temp/BijuuPreview.request";
 static LumiBijuuPreview(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;if(File.Exists(Request)){if(EditorApplication.isPlaying){EditorApplication.isPlaying=false;return;}File.Delete(Request);UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/3D.unity");Build();EditorApplication.isPaused=false;SessionState.SetBool("Lumi.BijuuPreview",true);EditorApplication.isPlaying=true;}if(SessionState.GetBool("Lumi.BijuuPreview",false)&&EditorApplication.isPlaying){var game=UnityEngine.Object.FindObjectOfType<LumiGame>();if(game!=null){SessionState.SetBool("Lumi.BijuuPreview",false);game.StartCoroutine(Check(game));}}}
 [MenuItem("Naruto/Preview Matatabi and Gyuki")] public static void Build(){
 Directory.CreateDirectory("Logs/BijuuReferenceQA");Directory.CreateDirectory("Assets/Resources/LumiEnemies");AssetDatabase.Refresh();
 var reference=UnityEngine.Object.Instantiate(Resources.Load<GameObject>("LumiEnemies/Kurama"));float height=LumiKuramaPreview.MeasureBody(reference,true).size.y;UnityEngine.Object.DestroyImmediate(reference);
 foreach(string name in new[]{"Matatabi","Gyuki"}){
 string path="Assets/Art/BijuuReference/Models/"+name+".fbx";var importer=AssetImporter.GetAtPath(path) as ModelImporter;importer.animationType=ModelImporterAnimationType.Legacy;importer.importAnimation=true;importer.isReadable=true;importer.importCameras=false;importer.importLights=false;importer.addCollider=false;importer.materialImportMode=ModelImporterMaterialImportMode.None;var clips=importer.defaultClipAnimations;foreach(var clip in clips){clip.name=clip.name.EndsWith("Idle")?"Idle":clip.name.EndsWith("Run")?"Run":"Attack";clip.loopTime=clip.name!="Attack";clip.wrapMode=clip.loopTime?WrapMode.Loop:WrapMode.Once;}importer.clipAnimations=clips;importer.SaveAndReimport();
 var root=new GameObject(name+" animated enemy preview");try{
 var artwork=new GameObject("Normalized artwork").transform;artwork.SetParent(root.transform,false);var model=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(path),artwork,false);var anim=model.GetComponentInChildren<Animation>();anim.playAutomatically=false;anim.Play("Idle");anim["Idle"].time=0;anim.Sample();anim.Stop();Transform head=null,mouth=null;foreach(var bone in model.GetComponentsInChildren<Transform>()){if(bone.name=="Head")head=bone;if(bone.name=="Bijuu Mouth")mouth=bone;}Vector3 forward=mouth.position-head.position;forward.y=0;artwork.rotation=Quaternion.FromToRotation(forward.normalized,Vector3.forward);Bounds bounds=LumiKuramaPreview.MeasureBody(model,true);float scale=height/bounds.size.y;artwork.localScale*=scale;artwork.localPosition=Vector3.down*bounds.min.y*scale;
 string matPath="Assets/Art/BijuuReference/"+name+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(matPath);if(mat==null){mat=new Material(Shader.Find("Lumi/Bijuu Vertex Color"));AssetDatabase.CreateAsset(mat,matPath);}mat.SetFloat("_Glow",name=="Matatabi"?.35f:.05f);mat.SetColor("_RimColor",name=="Matatabi"?new Color(0,.8f,1):new Color(.4f,.12f,.35f));EditorUtility.SetDirty(mat);foreach(var skin in model.GetComponentsInChildren<SkinnedMeshRenderer>()){if(skin.sharedMesh.colors.Length==0)throw new Exception("Vertex colors missing for "+name);var materials=skin.sharedMaterials;for(int i=0;i<materials.Length;i++)materials[i]=mat;skin.sharedMaterials=materials;skin.updateWhenOffscreen=true;var box=skin.localBounds;box.Expand(3);skin.localBounds=box;}var driver=root.AddComponent<LumiImportedBijuuMotion>();driver.Ranged=name=="Gyuki";PrefabUtility.SaveAsPrefabAsset(root,"Assets/Resources/LumiEnemies/"+name+".prefab");
 }finally{UnityEngine.Object.DestroyImmediate(root);}}
 AssetDatabase.SaveAssets();File.WriteAllText("Logs/BijuuReferenceQA/Import.txt","PASS: new 3D volume meshes painted from image parts; retired original blockouts, skinned rigs and Idle/Run/Attack clips; body height normalized to Kurama; separate previews, live enemy lineup unchanged.");
 }
 static IEnumerator Check(LumiGame game){int oldCaptureRate=Time.captureFramerate;Time.captureFramerate=30;var errors=new List<string>();Application.LogCallback log=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;game.StartLevelForValidation(1);yield return null;foreach(var enemy in UnityEngine.Object.FindObjectsOfType<LumiEnemy>())enemy.enabled=false;game.VillageBoss.enabled=false;game.Player.enabled=false;game.CameraRig.SetFirstPerson(false);game.CameraRig.enabled=false;game.SetMouseLook(false);Vector3 origin=game.Player.transform.position+Vector3.forward*7;
 foreach(string name in new[]{"Matatabi","Gyuki"}){
 string output="Logs/BijuuReferenceQA/"+name;Directory.CreateDirectory(output+"/Frames");var root=new GameObject(name+" staged enemy",typeof(CharacterController));root.transform.SetParent(game.Player.transform.parent,true);root.transform.position=origin;var enemy=root.AddComponent<LumiEnemy>();enemy.Initialize(game,game.Player,name=="Matatabi"?LumiEnemyType.Sprout:LumiEnemyType.Ranger,1);enemy.enabled=false;foreach(Transform child in root.transform)UnityEngine.Object.Destroy(child.gameObject);yield return null;
 var visual=UnityEngine.Object.Instantiate(Resources.Load<GameObject>("LumiEnemies/"+name),root.transform,false);var driver=visual.GetComponent<LumiImportedBijuuMotion>();driver.Initialize(game,enemy);var skin=visual.GetComponentInChildren<SkinnedMeshRenderer>();var anim=visual.GetComponentInChildren<Animation>();foreach(var r in UnityEngine.Object.FindObjectsOfType<Renderer>())r.enabled=r.transform.IsChildOf(root.transform)||r.transform.IsChildOf(game.Player.transform);var floor=GameObject.CreatePrimitive(PrimitiveType.Cube);floor.transform.SetParent(root.transform.parent,true);floor.transform.position=origin+Vector3.down*.06f;floor.transform.localScale=new Vector3(30,.1f,30);floor.GetComponent<Renderer>().sharedMaterial=LumiFactory.Material("Bijuu studio floor",new Color(.21f,.24f,.29f));UnityEngine.Object.Destroy(floor.GetComponent<Collider>());
 var controller=root.GetComponent<CharacterController>();controller.height=1.8f;controller.radius=.65f;controller.center=Vector3.up*.9f;var refModel=UnityEngine.Object.Instantiate(Resources.Load<GameObject>("LumiEnemies/Kurama"));float height=LumiKuramaPreview.MeasureBody(refModel,true).size.y;UnityEngine.Object.Destroy(refModel);float ratio=LumiKuramaPreview.MeasureBody(visual,true).size.y/height;File.WriteAllText(output+"/Size.txt","Body height / Kurama: "+ratio.ToString("F3")+"; skin bones "+skin.bones.Length+"; vertices "+skin.sharedMesh.vertexCount);if(Mathf.Abs(ratio-1)>.03f)errors.Add(name+" height mismatch");foreach(string clip in new[]{"Idle","Run","Attack"})if(anim[clip]==null)errors.Add(name+" missing "+clip);SetPlayer(game,origin+Vector3.right*3.1f);Capture(game,origin+Vector3.right*1.2f,output+"/Comparison.png");int frame=0;float age=0,next=0,minGround=float.PositiveInfinity;while(age<.6f){age+=Time.deltaTime;if(age>=next){Capture(game,root.transform.position,output+"/Frames/"+(frame++).ToString("D4")+".png");next+=.1f;}yield return null;}
 age=0;next=0;while(age<2.4f){controller.Move(Vector3.forward*(name=="Matatabi"?2.4f:1.8f)*Time.deltaTime);age+=Time.deltaTime;minGround=Mathf.Min(minGround,LumiKuramaPreview.MeasureBody(visual,true).min.y-root.transform.position.y);if(age>=next){Capture(game,root.transform.position,output+"/Frames/"+(frame++).ToString("D4")+".png");next+=.1f;}yield return null;}if(minGround<-.025f)errors.Add(name+" feet penetrate floor "+minGround);if(Vector3.Distance(origin,root.transform.position)<1)errors.Add(name+" movement blocked");if(!anim.IsPlaying("Run"))errors.Add(name+" running animation missing");Capture(game,root.transform.position,output+"/Run.png");SetPlayer(game,root.transform.position+Vector3.forward*(driver.Ranged?7:1.65f));int before=game.Player.Health+game.Player.Armor;driver.Attack(game.Player,name=="Matatabi"?1:3);age=0;next=0;while(age<(driver.Ranged?2.6f:1.4f)){age+=Time.deltaTime;if(age>=next){Capture(game,root.transform.position+Vector3.forward*(driver.Ranged?2:0),output+"/Frames/"+(frame++).ToString("D4")+".png");next+=.1f;}yield return null;}if(game.Player.Health+game.Player.Armor>=before)errors.Add(name+" attack did not damage target");if(driver.Busy)errors.Add(name+" attack failed recovery");Physics.SyncTransforms();var traceObj=new GameObject("Bijuu collision test");var trace=traceObj.AddComponent<LumiProjectile>();trace.enabled=false;trace.Initialize(game,Vector3.forward,22,4,true,game.Player.transform);foreach(float side in new[]{-.8f,0,.8f}){var b=driver.BodyHitbox.bounds;Vector3 point=b.center+Vector3.right*b.extents.x*side;if(!trace.Trace(point-Vector3.forward*4,Vector3.forward,8,out RaycastHit hit,.13f)||hit.collider.GetComponentInParent<LumiEnemy>()!=enemy)errors.Add(name+" body edge missed "+side);}UnityEngine.Object.Destroy(traceObj);File.WriteAllText(output+"/Validation.txt","Ground minimum "+minGround.ToString("F4")+" m; movement, clips, attack damage, recovery, colored skin and body collision checked.\n"+string.Join("\n",errors));UnityEngine.Object.Destroy(root);UnityEngine.Object.Destroy(floor);yield return null;
 }
 Application.logMessageReceived-=log;File.WriteAllText("Logs/BijuuReferenceQA/Validation.txt",(errors.Count==0?"PASS":"FAIL")+"\nReference-based Matatabi melee and Gyuki ranged animated previews.\n"+string.Join("\n",errors));Time.captureFramerate=oldCaptureRate;game.ShowLevelMenu();EditorApplication.isPlaying=false;
 }
 static void SetPlayer(LumiGame game,Vector3 point){game.Player.Controller.enabled=false;game.Player.transform.position=point;game.Player.transform.rotation=Quaternion.LookRotation(Vector3.back);game.Player.Controller.enabled=true;}
 static void Capture(LumiGame game,Vector3 center,string path){var camera=game.CameraRig.ViewCamera;camera.transform.position=center+new Vector3(4.3f,2.8f,5.7f);camera.transform.LookAt(center+Vector3.up*1.1f);camera.fieldOfView=48;var rt=RenderTexture.GetTemporary(1280,900,24);var old=camera.targetTexture;var active=RenderTexture.active;var tex=new Texture2D(1280,900,TextureFormat.RGB24,false);try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1280,900),0,0);tex.Apply();File.WriteAllBytes(path,tex.EncodeToPNG());}finally{camera.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);UnityEngine.Object.Destroy(tex);}}
}
