using System;using System.IO;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEditor;using UnityEngine;using LumiAdventure;
[InitializeOnLoad] public static class LumiBossSkillsValidation {
 static LumiBossSkillsValidation(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;if(File.Exists("Temp/BossSkillsValidation.request")){if(EditorApplication.isPlaying){EditorApplication.isPlaying=false;return;}File.Delete("Temp/BossSkillsValidation.request");SessionState.SetBool("Lumi.BossSkillsQA",true);EditorApplication.isPlaying=true;}if(SessionState.GetBool("Lumi.BossSkillsQA",false)&&EditorApplication.isPlaying){var game=UnityEngine.Object.FindObjectOfType<LumiGame>();if(game!=null){SessionState.SetBool("Lumi.BossSkillsQA",false);game.StartCoroutine(Check(game));}}}
 static void Set(object o,string field,object value){o.GetType().GetField(field,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(o,value);}
 static void Teleport(CharacterController c,Vector3 p){c.enabled=false;c.transform.position=p;c.enabled=true;Physics.SyncTransforms();}
 static IEnumerator Check(LumiGame game){var errors=new List<string>();var results=new List<string>();Application.LogCallback log=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;
 for(int level=1;level<=5;level++)for(int phase=1;phase<=2;phase++){
 game.StartLevelForValidation(level);yield return null;foreach(var enemy in UnityEngine.Object.FindObjectsOfType<LumiEnemy>())enemy.enabled=false;var boss=game.VillageBoss;boss.enabled=false;game.Player.enabled=false;game.CameraRig.SetFirstPerson(false);game.CameraRig.enabled=false;game.SetMouseLook(false);
 Vector3 at=boss.transform.position+Vector3.forward*3;Teleport(game.Player.Controller,at);Set(boss,"combatTarget",game.Player);if(phase==2)boss.TakeDamage(boss.MaxHealth/2+1,boss.AimPoint);Set(boss,"skillSequence",0);int beforeResources=game.Player.Health+game.Player.Armor;
 var cloneObj=new GameObject("Skill QA clone",typeof(CharacterController));cloneObj.transform.SetParent(game.Player.transform.parent,true);cloneObj.transform.position=at+Vector3.right*.5f;var clone=cloneObj.AddComponent<LumiShadowClone>();clone.Initialize(game,game.Player,20);clone.enabled=false;LumiShadowClone.Active.Add(clone);float cloneHP=clone.Health;
 var motion=boss.GetComponentInChildren<LumiInfantryMotion>();if(motion==null||!motion.RigConfigured)errors.Add("Missing current boss joint rig "+level);
 Transform arm=null;foreach(var t in boss.GetComponentsInChildren<Transform>())if(t.name=="Right arm")arm=t;Quaternion rest=arm!=null?arm.localRotation:Quaternion.identity;
 boss.StartCoroutine((IEnumerator)typeof(LumiVillageBoss).GetMethod("ExclusiveSkill",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(boss,null));yield return new WaitForSeconds(.7f);
 if(arm==null||Quaternion.Angle(rest,arm.localRotation)<5)errors.Add("No cast arm animation "+level+"/"+phase);
 yield return new WaitForSeconds(.8f);if(game.Player.Health+game.Player.Armor>=beforeResources)errors.Add("Skill missed centered player "+level+"/"+phase);if(clone!=null && clone.Health>=cloneHP)errors.Add("Skill missed centered clone "+level+"/"+phase);string key=LumiBossAssetsBuild.Names[level-1]+"_Skill"+phase;GameObject effect=GameObject.Find(key+" active");if(effect==null)errors.Add("No active skill "+key);else if(effect.GetComponentsInChildren<Renderer>().Length==0)errors.Add("Missing skill mesh "+key);
 var camera=game.CameraRig.ViewCamera;camera.transform.position=at+new Vector3(12,10,13);camera.transform.LookAt(at+Vector3.up*2);camera.fieldOfView=50;var rt=new RenderTexture(1000,700,24);camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;var tex=new Texture2D(1000,700,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1000,700),0,0);tex.Apply();File.WriteAllBytes("Logs/BossAssetsQA/"+key+".png",tex.EncodeToPNG());camera.targetTexture=null;RenderTexture.active=null;UnityEngine.Object.Destroy(rt);UnityEngine.Object.Destroy(tex);
 game.PauseGame();Vector3 paused=boss.transform.position;yield return new WaitForSecondsRealtime(.12f);if(boss.transform.position!=paused)errors.Add("Paused boss moved");game.ResumeGame();yield return new WaitForSeconds(.12f);results.Add(key+": mesh, cast animation, player/clone damage and pause checked.");boss.StopAllCoroutines();typeof(LumiVillageBoss).GetMethod("ClearCast",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(boss,null);
 boss.StartCoroutine((IEnumerator)typeof(LumiVillageBoss).GetMethod("ExclusiveSkill",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(boss,null));yield return new WaitForSeconds(.1f);boss.StopAllCoroutines();typeof(LumiVillageBoss).GetMethod("ClearCast",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(boss,null);yield return null;if(GameObject.Find("Boss attack warning")!=null)errors.Add("Cancelled warning remains "+key);
 boss.TakeDamage(boss.MaxHealth,boss.AimPoint);yield return null;if(effect!=null)errors.Add("Dead boss left its damaging skill "+key);
 }
 Application.logMessageReceived-=log;File.WriteAllText("Logs/BossAssetsQA/Validation.txt",(errors.Count==0?"PASS":"FAIL")+"\n"+string.Join("\n",results)+"\n"+string.Join("\n",errors));game.ShowLevelMenu();EditorApplication.isPlaying=false;
 }
}