using System;using System.IO;using System.Collections;using System.Collections.Generic;using UnityEditor;using UnityEngine;using LumiAdventure;
[InitializeOnLoad] public static class LumiBijuuLiveValidation {
 const string Request="Temp/BijuuLive.request";
 [Serializable] public class SkinData{public Vector3[] vertices;public SkinWeight[] weights;}
 [Serializable] public struct SkinWeight{public int b0,b1,b2,b3;public float w0,w1,w2,w3;}
 static void DumpSkin(string name,Mesh mesh){var weights=mesh.boneWeights;var data=new SkinData{vertices=mesh.vertices,weights=new SkinWeight[weights.Length]};for(int i=0;i<weights.Length;i++){var w=weights[i];data.weights[i]=new SkinWeight{b0=w.boneIndex0,b1=w.boneIndex1,b2=w.boneIndex2,b3=w.boneIndex3,w0=w.weight0,w1=w.weight1,w2=w.weight2,w3=w.weight3};}Directory.CreateDirectory("Logs/BijuuLiveQA/SkinData");File.WriteAllText("Logs/BijuuLiveQA/SkinData/"+name+".json",JsonUtility.ToJson(data));}
 [MenuItem("Naruto/Optimize approved Bijuu prefabs")] public static void OptimizePrefabs(){var tags=new SerializedObject(AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset")[0]);tags.FindProperty("layers").GetArrayElementAtIndex(31).stringValue="EnemyDamage";tags.ApplyModifiedProperties();Directory.CreateDirectory("Assets/Art/BijuuReference/Optimized");var report=new List<string>();foreach(string name in new[]{"Matatabi","Gyuki"}){string path="Assets/Resources/LumiEnemies/"+name+".prefab";var root=PrefabUtility.LoadPrefabContents(path);try{foreach(var skin in root.GetComponentsInChildren<SkinnedMeshRenderer>()){var source=skin.sharedMesh;DumpSkin(name,source);if(source.subMeshCount<=1)continue;var mats=skin.sharedMaterials;foreach(var mat in mats)if(mat!=mats[0])throw new Exception("Cannot merge different materials for "+name);string meshPath="Assets/Art/BijuuReference/Optimized/"+name+"-Skin.asset";var mesh=AssetDatabase.LoadAssetAtPath<Mesh>(meshPath);if(mesh==null){mesh=UnityEngine.Object.Instantiate(source);mesh.name=name+" combined skin";int[] indices=mesh.triangles;mesh.subMeshCount=1;mesh.SetTriangles(indices,0,false);AssetDatabase.CreateAsset(mesh,meshPath);}report.Add(name+": "+source.subMeshCount+" submeshes -> "+mesh.subMeshCount+"; vertices "+mesh.vertexCount);skin.sharedMesh=mesh;skin.sharedMaterials=new[]{mats[0]};skin.updateWhenOffscreen=false;}PrefabUtility.SaveAsPrefabAsset(root,path);}finally{PrefabUtility.UnloadPrefabContents(root);}}var kuramaPrefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Resources/LumiEnemies/Kurama.prefab");DumpSkin("Kurama",kuramaPrefab.GetComponentInChildren<SkinnedMeshRenderer>().sharedMesh);AssetDatabase.SaveAssets();Directory.CreateDirectory("Logs/BijuuLiveQA");if(report.Count>0)File.WriteAllText("Logs/BijuuLiveQA/RenderOptimization.txt",string.Join("\n",report));}
 static LumiBijuuLiveValidation(){EditorApplication.update+=Poll;}
 static void Poll(){if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;if(File.Exists(Request)){if(EditorApplication.isPlaying){EditorApplication.isPlaying=false;return;}File.Delete(Request);OptimizePrefabs();UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/3D.unity");SessionState.SetBool("Lumi.BijuuLive",true);EditorApplication.isPaused=false;EditorApplication.isPlaying=true;}if(SessionState.GetBool("Lumi.BijuuLive",false)&&EditorApplication.isPlaying){var g=UnityEngine.Object.FindObjectOfType<LumiGame>();if(g!=null){SessionState.SetBool("Lumi.BijuuLive",false);g.StartCoroutine(Check(g));}}}
 static IEnumerator Check(LumiGame game){Directory.CreateDirectory("Logs/BijuuLiveQA");var errors=new List<string>();var results=new List<string>();Application.LogCallback log=(m,s,t)=>{if(t==LogType.Error||t==LogType.Exception)errors.Add(m);};Application.logMessageReceived+=log;game.StartLevelForValidation(1);yield return null;
 foreach(var e in UnityEngine.Object.FindObjectsOfType<LumiEnemy>()){if((e.EnemyType==LumiEnemyType.Golem&&e.GetComponentInChildren<LumiKuramaMotion>()==null)||(e.EnemyType!=LumiEnemyType.Golem&&e.GetComponentInChildren<LumiImportedBijuuMotion>()==null))errors.Add("Live spawn has old visual");UnityEngine.Object.Destroy(e.gameObject);}game.VillageBoss.enabled=false;game.Player.enabled=false;game.CameraRig.SetFirstPerson(false);game.CameraRig.enabled=false;game.SetMouseLook(false);yield return null;
 Vector3 origin=game.Player.transform.position+Vector3.forward*7; var perf=new List<string>(); var strong=new GameObject("Kurama benchmark",typeof(CharacterController));strong.transform.SetParent(game.Player.transform.parent,true);strong.transform.position=origin+Vector3.right*10;var strongEnemy=strong.AddComponent<LumiEnemy>();strongEnemy.Initialize(game,game.Player,LumiEnemyType.Golem,1);strongEnemy.enabled=false;var k=strong.GetComponentInChildren<LumiKuramaMotion>();if(k==null)errors.Add("Golem did not use Kurama");else{perf.Add("Kurama old "+Benchmark(k,"UpdateBodyHitboxReference"));perf.Add("Kurama new "+Benchmark(k,"UpdateBodyHitbox"));CompareHits(k,"UpdateBodyHitbox",errors);}UnityEngine.Object.Destroy(strong);
 foreach(var kind in new[]{LumiEnemyType.Sprout,LumiEnemyType.Ranger}){
 string name=kind==LumiEnemyType.Sprout?"Matatabi":"Gyuki";var root=new GameObject(name+" live AI validation",typeof(CharacterController));root.transform.SetParent(game.Player.transform.parent,true);root.transform.position=origin;var enemy=root.AddComponent<LumiEnemy>();enemy.Initialize(game,game.Player,kind,1);var motion=root.GetComponentInChildren<LumiImportedBijuuMotion>();if(motion==null){errors.Add(name+" missing live driver");UnityEngine.Object.Destroy(root);continue;}if(motion.Ranged!=(kind==LumiEnemyType.Ranger))errors.Add(name+" role mismatch");perf.Add(name+" old "+Benchmark(motion,"RefreshHitsReference"));perf.Add(name+" new "+Benchmark(motion,"RefreshHits"));CompareHits(motion,"RefreshHits",errors);var anim=root.GetComponentInChildren<Animation>();foreach(string clip in new[]{"Idle","Run","Attack"})if(anim[clip]==null)errors.Add(name+" missing "+clip);
 float offset=kind==LumiEnemyType.Sprout?5:12;SetPlayer(game,origin+Vector3.forward*offset);Vector3 start=root.transform.position;bool ran=false,attacked=false;int before=game.Player.Health+game.Player.Armor;float age=0;while(age<8){age+=Time.deltaTime;ran|=anim.IsPlaying("Run");attacked|=motion.Busy;if(attacked&&game.Player.Health+game.Player.Armor<before)break;yield return null;}float travelled=Vector3.Distance(start,root.transform.position);var flags=System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance;results.Add(name+" debug: root "+root.transform.position+", player "+game.Player.transform.position+", aim "+enemy.AimPoint+", body "+motion.BodyHitbox.bounds+", melee reach "+motion.WithinMeleeReach(game.Player,.8f)+", LOS "+typeof(LumiEnemy).GetMethod("HasLineOfSight",flags).Invoke(enemy,null));if(travelled<.5f||!ran)errors.Add(name+" AI did not run");if(!attacked)errors.Add(name+" AI did not attack");if(game.Player.Health+game.Player.Armor>=before)errors.Add(name+" AI failed damage");Capture(game,root.transform.position,"Logs/BijuuLiveQA/"+name+"-Gameplay.png");
 enemy.enabled=false;motion.CancelAttack();yield return null;Physics.SyncTransforms();var traceObj=new GameObject("Live bijuu projectile trace");var trace=traceObj.AddComponent<LumiProjectile>();trace.enabled=false;trace.Initialize(game,Vector3.forward,22,4,true,game.Player.transform);int hits=0;foreach(float side in new[]{-.8f,0,.8f}){Bounds b=motion.BodyHitbox.bounds;Vector3 p=b.center+Vector3.right*b.extents.x*side;if(trace.Trace(p-Vector3.forward*4,Vector3.forward,8,out RaycastHit hit,.13f)&&hit.collider.GetComponentInParent<LumiEnemy>()==enemy)hits++;}if(hits!=3)errors.Add(name+" collider edges missed");int hp=enemy.MaxHealth;enemy.TakeDamage(4,enemy.AimPoint);if(Mathf.Abs(enemy.HealthFraction-(hp-4)/(float)hp)>.001f)errors.Add(name+" damage reception mismatch");results.Add(name+": actual live factory, AI Run, attack damage "+(before-game.Player.Health-game.Player.Armor)+", travelled "+travelled.ToString("F2")+"m, body hit edges "+hits+"/3, received damage; HP "+hp);UnityEngine.Object.Destroy(traceObj);UnityEngine.Object.Destroy(root);yield return null;
 }
 foreach(int level in new[]{1,5}){game.StartLevelForValidation(level);yield return null;game.Player.enabled=false;game.VillageBoss.enabled=false;yield return new WaitForSecondsRealtime(1);var frames=new List<float>();float until=Time.realtimeSinceStartup+3;while(Time.realtimeSinceStartup<until){frames.Add(Time.unscaledDeltaTime*1000);yield return null;}frames.Sort();float sum=0;foreach(float frame in frames)sum+=frame;int count=UnityEngine.Object.FindObjectsOfType<LumiEnemy>().Length;perf.Add("Map "+level+": "+count+" enemies, Editor avg "+(sum/frames.Count).ToString("F2")+" ms/frame, p95 "+frames[Mathf.Min(frames.Count-1,Mathf.FloorToInt(frames.Count*.95f))].ToString("F2")+" ms, approx "+(1000*frames.Count/sum).ToString("F1")+" FPS");foreach(var e in UnityEngine.Object.FindObjectsOfType<LumiEnemy>())if(e.EnemyType==LumiEnemyType.Golem?e.GetComponentInChildren<LumiKuramaMotion>()==null:e.GetComponentInChildren<LumiImportedBijuuMotion>()==null)errors.Add("Map "+level+" wrong enemy visual");}File.WriteAllText("Logs/BijuuLiveQA/Performance.txt",string.Join("\n",perf));Application.logMessageReceived-=log;File.WriteAllText("Logs/BijuuLiveQA/Validation.txt",(errors.Count==0?"PASS":"FAIL")+"\n"+string.Join("\n",results)+"\n"+string.Join("\n",errors));game.ShowLevelMenu();EditorApplication.isPlaying=false;
 }
 static void CompareHits(Component c,string method,List<string> errors){var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;var old=c.GetType().GetMethod(method+"Reference",flags);var fast=c.GetType().GetMethod(method,flags);var anim=c.GetComponentInChildren<Animation>();var boxes=c.GetComponents<BoxCollider>();var saved=new Bounds[boxes.Length];var renderer=c.GetComponentInChildren<SkinnedMeshRenderer>();foreach(string clip in new[]{"Idle","Run","Attack"})foreach(float fraction in new[]{0f,.33f,.67f}){anim.Play(clip);anim[clip].time=anim[clip].length*fraction;anim.Sample();old.Invoke(c,null);for(int i=0;i<boxes.Length;i++)saved[i]=boxes[i].bounds;fast.Invoke(c,null);for(int i=0;i<boxes.Length;i++){var b=boxes[i].bounds;if((saved[i].min-b.min).magnitude>.025f||(saved[i].max-b.max).magnitude>.025f){errors.Add(c.GetType().Name+" native hitbox mismatch scale "+renderer.transform.lossyScale+" mesh "+renderer.sharedMesh.bounds+" "+clip+" group "+i+" old "+saved[i]+" fast "+b);return;}}}anim.Play("Idle");anim["Idle"].time=0;anim.Sample();fast.Invoke(c,null);}
 static string Benchmark(Component c,string method){var m=c.GetType().GetMethod(method,System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);m.Invoke(c,null);var clock=System.Diagnostics.Stopwatch.StartNew();for(int i=0;i<30;i++)m.Invoke(c,null);clock.Stop();return c.GetType().Name+": "+(clock.Elapsed.TotalMilliseconds/30).ToString("F4")+" ms/update";}
 static void SetPlayer(LumiGame game,Vector3 p){game.Player.Controller.enabled=false;game.Player.transform.position=p;game.Player.Controller.enabled=true;}
 static void Capture(LumiGame game,Vector3 center,string path){var c=game.CameraRig.ViewCamera;c.transform.position=center+new Vector3(4.3f,2.8f,5.7f);c.transform.LookAt(center+Vector3.up*1.1f);var rt=RenderTexture.GetTemporary(1280,900,24);var old=c.targetTexture;var active=RenderTexture.active;var tex=new Texture2D(1280,900,TextureFormat.RGB24,false);try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1280,900),0,0);tex.Apply();File.WriteAllBytes(path,tex.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;RenderTexture.ReleaseTemporary(rt);UnityEngine.Object.Destroy(tex);}}
}









